### PR TITLE
Trra 121/treq detail

### PR DESCRIPTION
**Pull request by aprigge**
Added TravelRequest detail page which links from the employee detail page.

### CODE REVIEW

**Comment by aprigge** [comment]
I see that the coveralls now isn't passing, although I did add tests. Advice for test improvements?

**Comment by akohler** [comment]
@aprigge The tyranny of test metrics......

The coverage barely decreased.  Here are the current and previous coveralls stats:
#103: 1068 of 1094 relevant lines covered (97.62%) 
#102: 1054 of 1079 relevant lines covered (97.68%) 

I think the tests you added are right in line with tests for similar functionality.  From my POV, this tiny decrease should not block approval of this PR - but get @joshuago78  to give the final verdict.

**Comment by aprigge** [comment]
Thanks, @akohler. Was @joshuago78 's comment in stand up an approval?

**Comment by akohler** [comment]
He mentioned 98% coverage, but we're at 97.6% and your changes did not significantly reduce that - it'd take several new tests to push that back above 98%.

The only reason I haven't merged this already is just in case you want him to look at the code as well.  If not, I think you can go ahead and merge - or let me know and I'll click the button :)

**Comment by aprigge** [comment]
Thanks, @akohler. I feel fine with a merge. Can you press the button (I don't want to break that rule too)?

**Pull request merged**
