### PR TITLE
Trra 61/allocations report

### PR DESCRIPTION
**Pull request by joshuago78**
To test this out:

- install the new packages: `pip install -r requirements`
- flush your database `python manage.py flush`
- apply migrations: `python manage.py migrate`
- load the updated fixture data: `python manage.py loaddata sample_data`
- run the dev server: `python manage.py runserver`
- view the unit allocation and expenditure reports at the following URLs:
    - http://127.0.0.1:8000/unit/1/
    - http://127.0.0.1:8000/unit/2/
    - http://127.0.0.1:8000/unit/3/

The `unit_report` function operates in a generic way to pull in the data for the currently viewed unit and split it by subunits. Staff in subunits of subunits are aggregated into those top subunits

### CODE REVIEW

**Comment by joshuago78** [comment]
I just realized I never clean up the header. Go ahead and play around with what is here while I work on that

**Comment by joshuago78** [comment]
Thanks @akohler. I have not yet added restrictions to the view. I was going to do that in a followup PR, but I see that it is part of the acceptance criteria for TRRA-61. I'll see if I can add it by Monday.

Also, that failed test does look like a locale issue.

**Comment by joshuago78** [comment]
OK, I have added a check for manager or "supermanager" status to view the unit detail page

**Comment by joshuago78** [comment]
I realized today that the unit reports as they are now, do not show employees with no travel requests. I think that is OK for now, but we will need to refactor the query and report to include members of the unit with no travel. I thought about how to change the query and it seems difficult. I am new to doing aggregations in the Django code. I will likely just use a raw SQL statement to perform the query instead of using the `values()` and `annotate()` methods. We can do all of that in a follow up ticket rather than try to refactor this PR

**Comment by akohler** [comment]
@joshuago78 Is this PR now finished and ready for review and possible merge, or do you expect to add more commits first?

**Comment by joshuago78** [comment]
Sorry for the ongoing updates. I may try to tweak it again tonight. Let's say that if I don't have anything in by Monday morning, we will merge this as is.

**Comment by akohler** [comment]
I think this is good enough to merge.  Improvements can be made in the next sprint.

I loaded the historical data, which exposes a couple of problems:
* We need an authoritative list of units and their managers.  Without unit managers, unit reports don't work.
* The unit reports cover only the current FY; the historical data is all from the 2 previous FYs.
* Employees in unit reports need to be sorted (or sortable) by last name.

Also, `test_currency` still fails on my machine, despite the `setlocale` in `settings.py`.  Since it only affects me so far, I'll try to track down a fix.

**Pull request merged**
