### PR TITLE
Trra 171/unit report changes

### PR DESCRIPTION
**Pull request by joshuago78**
We updated the ticket so that it is scoped to the unit report only and also incorporates requirements form TRRA-168

### CODE REVIEW

**Comment by aprigge** [comment]
@joshuago78 I think we need to change the tests too (14 errors). Should we do that on this same branch?

**Comment by joshuago78** [comment]
Yes, tests should be updated in the same branch. I will make some edits. Although it appears that Travis tests passed.

**Comment by aprigge** [comment]
@joshuago78 Sounds good. I don't think the travis build passing is accurate. In the details it shows the 14 errors.

**Comment by akohler** [comment]
Yes, this is a problem I noticed a while ago but did not have time to investigate: Travis reports passing builds even when there are errors.  I'll create a ticket so I don't forget about it again.

14 errors confirmed locally.  Looks like a problem with the sample data, at least.

**Comment by aprigge** [comment]
@joshuago78 The footer of the unit report template should be using the unit totals and not the subunit totals(lines 123-138)

        `<tfoot>
            <tr>
                <th>Totals</th>
                <th></th>
                <th class="text-right">{{report.unit_totals.profdev_requested|currency}}</th>
                <th class="text-right">{{report.unit_totals.profdev_spent|currency}}</th>
                <th class="text-right">{{report.unit_totals.admin_requested|currency}}</th>
                <th class="text-right">{{report.unit_totals.admin_spent|currency}}</th>
                <th class="text-right">{{report.unit_totals.total_requested|currency}}</th>
                <th class="text-right">{{report.unit_totals.total_spent|currency}}</th>
                <th class="text-right">{{report.unit_totals.days_away}}</th>
            </tr>
        </tfoot>`

**Pull request merged**
