### PR TITLE
Trra 154/reports totals

### PR DESCRIPTION
**Pull request by aprigge**
Implemented Josh's fix for aggregations.  Employee detail page data now matches all reports.

### CODE REVIEW

**Comment by joshuago78** [comment]
These look correct. I would like tests added to prove that the numbers add up correctly. I think you should just create a second set of fixture data to test these specific queries. Create a set of employees, some with multiple approved admin trips, some with multiple approved prof-dev, some with multiples closed admin, etc.

**Comment by aprigge** [comment]
@joshuago78, sounds good. I'll add those.

**Comment by aprigge** [comment]
@akohler or @joshuago78 I've added additional sample data to the fixtures and included another test if one of you could take a look. Thanks!

**Comment by aprigge** [comment]
Thanks, @akohler. I'll leave those choices up to @joshuago78. Though I do think it could be helpful to move it to test first and have Mike review

**Comment by joshuago78** [comment]
Let's push it to prod. The math in prod is wrong, so if this math is also wrong, we haven't made it any worse. We definitely want Mike to look through prod data and verify that the math is correct. It doesn't matter if the prod data is wrong. This change is about the math, not the data. So he can look at the potentially bad data and just ensure that it is adding things up correctly.

**Pull request merged**
