### PR TITLE
Converted Dashboard to EmployeeDetailView and added the necessary res…

### PR DESCRIPTION
**Pull request by joshuago78**
…trictions and features. Closes TRRA-107

### CODE REVIEW

**Comment by joshuago78** [comment]
Why are coverage checks not running?

**Comment by aprigge** [comment]
I see that all checks have passed; can it do that without running the coverage checks? The report pages look good to me. I think the base.html needs to be updated next and the Employee report(s) given a link and 'Dashboard' taken out.

I'll let Andy do a check as well.

**Comment by joshuago78** [comment]
OK, I updated the base.html file. I will work on an EmployeeList page next so that managers can navigate to an individual page

**Comment by akohler** [comment]
> 
> 
> Why are coverage checks not running?

@joshuago78 I see from the build output https://travis-ci.com/UCLALibrary/terra/builds/132047339#L882 "The program 'coveralls' is currently not installed. To run 'coveralls' please ask your administrator to install the package 'ruby-coveralls'"

Maybe the various changes @sgurnick and I made to the Travis/Docker build sequence have caused `coveralls` to be unavailable to the image when Travis gets to that point?

**Comment by sgurnick** [comment]
Based on the travis job log output, it appears the `coveralls` command is running within the context of the Travis VM that is being spun-up and not within the Docker container. Is this what we expect or should coveralls instead run inside the container?

**Comment by joshuago78** [comment]
It should run with the code, so inside the container

**Comment by sgurnick** [comment]
Please correct me if I'm mistaken, but I believe [this line](https://github.com/UCLALibrary/terra/blob/8fcd5db6c2323665f83912e0d7980eb3412b7164/.travis/build_and_test.sh#L35) in `.travis/build_and_test.sh` is calling `coveralls` to run inside the container. 

Are we seeing indications that this is not working as we expect? Perhaps that last coveralls line that Andy found is superfluous and can be removed?

**Comment by joshuago78** [comment]
Yes that is running coverage which actually analyzes the code. However, [this line](https://github.com/UCLALibrary/terra/blob/8fcd5db6c2323665f83912e0d7980eb3412b7164/.travis.yml#L11) is the one that send the report to Coveralls and it is being run in the VM not the container, which has the necessary Python package.

**Comment by joshuago78** [comment]
FYI, I went ahead and added those hyperlinks now

**Pull request merged**
